CREATE TABLE INVOICE (
    ID SERIAL PRIMARY KEY,
    PRODUCT_ID INTEGER NOT NULL REFERENCES PRODUCT(ID) ON DELETE RESTRICT,
    ORDERS_ID INTEGER NOT NULL REFERENCES ORDERS(ID) ON DELETE RESTRICT,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(12,2) NOT NULL
);