CREATE TABLE ORDERS(
    ID SERIAL PRIMARY KEY,
    PRODUCT_ID INTEGER REFERENCES PRODUCT(ID) ON DELETE RESTRICT,
    QUANTITY INTEGER,
    USER_ID INTEGER REFERENCES USERS(ID) ON DELETE RESTRICT,
    ORDER_STATUS BOOL
);